# docker-compose.yml

version: "3.8" # Specify the Docker Compose version

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # Ensure Dockerfile is named correctly
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env # Specify the path to your .env file
    volumes:
      - ./backend:/app # Mount backend code for live-reloading (optional)
      - backend-node-modules:/app/node_modules # Named volume for backend
    networks:
      - neurotype-network

  frontend:
    build:
      context: ./frontend/neurotype
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Host port 3000 -> Container port 80 (NGINX)
    networks:
      - neurotype-network
    depends_on:
      - backend

volumes:
  backend-node-modules:

networks:
  neurotype-network:
    driver: bridge
