version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - backend-node-modules:/app/node_modules
    networks:
      - neurotype-network

  frontend:
    build:
      context: ./frontend/neurotype
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Host port 3000 -> Container port 80 (NGINX)
    networks:
      - neurotype-network
    depends_on:
      - backend

  cypress:
    image: cypress/included:12.14.0
    depends_on:
      - frontend
      - backend
    environment:
      - CYPRESS_baseUrl=http://frontend:80
    volumes:
      - ./frontend/neurotype:/e2e
    working_dir: /e2e
    command: npm run cypress:run
    networks:
      - neurotype-network

volumes:
  backend-node-modules:

networks:
  neurotype-network:
    driver: bridge
